repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.63.1
    hooks:
      - id: swiftlint
        entry: swiftlint --fix

  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.59.0
    hooks:
      - id: swiftformat
